const Characters = [
    { name: 'Any', id: 0 },
    { name: 'Mario', id: 1 },
    { name: 'DonkeyKong', id: 2 },
    { name: 'Link', id: 3 },
    { name: 'Samus', id: 4 },
    { name: 'DarkSamus', id: 5 },
    { name: 'Yoshi', id: 6 },
    { name: 'Kirby', id: 7 },
    { name: 'Fox', id: 8 },
    { name: 'Pikachu', id: 9 },
    { name: 'Luigi', id: 10 },
    { name: 'Ness', id: 11 },
    { name: 'CaptainFalcon', id: 12 },
    { name: 'Jigglypuff', id: 13 },
    { name: 'Peach', id: 14 },
    { name: 'Daisy', id: 15 },
    { name: 'Bowser', id: 16 },
    { name: 'IceClimbers', id: 17 },
    { name: 'Sheik', id: 18 },
    { name: 'Zelda', id: 19 },
    { name: 'DrMario', id: 20 },
    { name: 'Pichu', id: 21 },
    { name: 'Falco', id: 22 },
    { name: 'Marth', id: 23 },
    { name: 'Lucina', id: 24 },
    { name: 'YoungLink', id: 25 },
    { name: 'Ganondorf', id: 26 },
    { name: 'Mewtwo', id: 27 },
    { name: 'Roy', id: 28 },
    { name: 'Chrom', id: 29 },
    { name: 'MrGameAndWatch', id: 30 },
    { name: 'MetaKnight', id: 31 },
    { name: 'Pit', id: 32 },
    { name: 'DarkPit', id: 33 },
    { name: 'ZeroSuitSamus', id: 34 },
    { name: 'Wario', id: 35 },
    { name: 'Snake', id: 36 },
    { name: 'Ike', id: 37 },
    { name: 'PokemonTrainer', id: 38 },
    { name: 'DiddyKong', id: 39 },
    { name: 'Lucas', id: 40 },
    { name: 'Sonic', id: 41 },
    { name: 'KingDedede', id: 42 },
    { name: 'Olimar', id: 43 },
    { name: 'Lucario', id: 44 },
    { name: 'ROB', id: 45 },
    { name: 'ToonLink', id: 46 },
    { name: 'Wolf', id: 47 },
    { name: 'Villager', id: 48 },
    { name: 'MegaMan', id: 49 },
    { name: 'WiiFitTrainer', id: 50 },
    { name: 'RosalinaAndLuma', id: 51 },
    { name: 'LittleMac', id: 52 },
    { name: 'Greninja', id: 53 },
    { name: 'Palutena', id: 54 },
    { name: 'PacMan', id: 55 },
    { name: 'Robin', id: 56 },
    { name: 'Shulk', id: 57 },
    { name: 'BowserJr', id: 58 },
    { name: 'DuckHunt', id: 59 },
    { name: 'Ryu', id: 60 },
    { name: 'Ken', id: 61 },
    { name: 'Cloud', id: 62 },
    { name: 'Corrin', id: 63 },
    { name: 'Bayonetta', id: 64 },
    { name: 'Inkling', id: 65 },
    { name: 'Ridley', id: 66 },
    { name: 'Simon', id: 67 },
    { name: 'Richter', id: 68 },
    { name: 'KingKRool', id: 69 },
    { name: 'Isabelle', id: 70 },
    { name: 'Incineroar', id: 71 },
    { name: 'PiranhaPlant', id: 72 },
    { name: 'Joker', id: 73 },
    { name: 'Hero', id: 74 },
    { name: 'BanjoAndKazooie', id: 75 },
    { name: 'Terry', id: 76 },
    { name: 'Byleth', id: 77 },
    { name: 'MinMin', id: 78 },
    { name: 'Steve', id: 79 },
    { name: 'Sephiroth', id: 80 },
    { name: 'PyraAndMythra', id: 81 },
    { name: 'Kazuya', id: 82 },
    { name: 'Sora', id: 83 },
    { name: 'MiiBrawler', id: 84 },
    { name: 'MiiSwordfighter', id: 85 },
    { name: 'MiiGunner', id: 86 }
]

export default Characters;

// let Characters = [
//     "Any",
//     "Mario",
//     "DonkeyKong",
//     "Link",
//     "Samus",
//     "DarkSamus",
//     "Yoshi",
//     "Kirby",
//     "Fox",
//     "Pikachu",
//     "Luigi",
//     "Ness",
//     "CaptainFalcon",
//     "Jigglypuff",
//     "Peach",
//     "Daisy",
//     "Bowser",
//     "IceClimbers",
//     "Sheik",
//     "Zelda",
//     "DrMario",
//     "Pichu",
//     "Falco",
//     "Marth",
//     "Lucina",
//     "YoungLink",
//     "Ganondorf",
//     "Mewtwo",
//     "Roy",
//     "Chrom",
//     "MrGameAndWatch",
//     "MetaKnight",
//     "Pit",
//     "DarkPit",
//     "ZeroSuitSamus",
//     "Wario",
//     "Snake",
//     "Ike",
//     "PokemonTrainer",
//     "DiddyKong",
//     "Lucas",
//     "Sonic",
//     "KingDedede",
//     "Olimar",
//     "Lucario",
//     "ROB",
//     "ToonLink",
//     "Wolf",
//     "Villager",
//     "MegaMan",
//     "WiiFitTrainer",
//     "RosalinaAndLuma",
//     "LittleMac",
//     "Greninja",
//     "Palutena",
//     "PacMan",
//     "Robin",
//     "Shulk",
//     "BowserJr",
//     "DuckHunt",
//     "Ryu",
//     "Ken",
//     "Cloud",
//     "Corrin",
//     "Bayonetta",
//     "Inkling",
//     "Ridley",
//     "Simon",
//     "Richter",
//     "KingKRool",
//     "Isabelle",
//     "Incineroar",
//     "PiranhaPlant",
//     "Joker",
//     "Hero",
//     "BanjoAndKazooie",
//     "Terry",
//     "Byleth",
//     "MinMin",
//     "Steve",
//     "Sephiroth",
//     "PyraAndMythra",
//     "Kazuya",
//     "Sora",
//     "MiiBrawler",
//     "MiiSwordfighter",
//     "MiiGunner"
// ]

// let chars = []
// for(let i = 0; i < Characters.length; i++) {
//     chars.push({
//         name: Characters[i],
//         id: i
//     })
// }

// console.log(chars)